"""Pydantic-backed configuration loading.

Reads configs/.env from the current working directory or workspace, then falls
back to legacy .env files. Env-file parsing is built in, so python-dotenv is
not required.

Supported variables:
    OPENCOLLAB_MODEL      — default LLM model (e.g., "claude-sonnet-4-20250514")
    OPENCOLLAB_PROVIDER   — LLM provider ("openai", "anthropic")
    OPENCOLLAB_WIRE_PROTOCOL — "chat_completions" or "responses"
    OPENCOLLAB_API_KEY    — API key (also reads OPENAI_API_KEY /
                            ANTHROPIC_API_KEY / DASHSCOPE_API_KEY)
    OPENCOLLAB_BASE_URL   — API base URL (also reads OPENAI_BASE_URL)
    OPENCOLLAB_BUDGET     — default token budget
    OPENCOLLAB_TEMPERATURE — LLM sampling temperature (default 0.2)
    OPENCOLLAB_TOP_P      — LLM nucleus-sampling top_p (0..1; unset/empty → None,
                            i.e. the provider default, so the request is unchanged)
    OPENCOLLAB_MAX_OUTPUT_TOKENS — maximum tokens generated by one LLM call
    OPENCOLLAB_THINKING   — enable provider "thinking"/reasoning passthrough (bool, default off)
    OPENCOLLAB_THINKING_PARAMS — JSON object of extra request params sent when
                            thinking is on (default {"enable_thinking": true})
    OPENCOLLAB_LLM_TIMEOUT — provider request timeout in seconds
    OPENCOLLAB_REASONING_EFFORT — Responses reasoning effort
    OPENCOLLAB_LLM_MAX_RETRIES — transient provider retries per model turn
    OPENCOLLAB_LLM_CONNECT_TIMEOUT — provider connection timeout in seconds
    OPENCOLLAB_LLM_FIRST_EVENT_TIMEOUT — Responses first-event timeout
    OPENCOLLAB_LLM_STREAM_IDLE_TIMEOUT — Responses stream-idle timeout
    OPENCOLLAB_FILTER_MESSAGES — TUI: show only the selected agent's stream (bool)
    OPENCOLLAB_CONFIG_FILE — explicit path to an env file
"""

from __future__ import annotations

import json
import os
import stat
from pathlib import Path
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator

from opencollab.adapters.llm.providers import (
    is_anthropic,
    normalize_wire_protocol,
    required_env_key,
)
from opencollab.adapters.llm.types import DEFAULT_MAX_OUTPUT_TOKENS
from opencollab.adapters.safe_files import read_regular_text

MAX_DOTENV_BYTES = 1024 * 1024

# Authoritative LLM sampling-temperature default. Every runtime path resolves
# its effective temperature from here (env/.env override → per-role override),
# so this is the single source of truth referenced by SpawnConfig, workflow
# execution, and SDK consumers.
DEFAULT_TEMPERATURE = 0.2

# Authoritative top_p (nucleus-sampling) default. ``None`` means "do not send a
# top_p" so every existing request stays byte-for-byte unchanged — only an
# explicit OPENCOLLAB_TOP_P (or per-call override) adds the knob. Mirrors the
# temperature flow: resolved once here, then threaded through the LLM client,
# providers, and SDK consumers.
DEFAULT_TOP_P: float | None = None

# Provider "thinking"/reasoning passthrough. OFF by default so every existing
# runtime path is byte-for-byte unchanged. When enabled, ``DEFAULT_THINKING_PARAMS``
# is the request payload sent to the OpenAI-compatible API as ``extra_body`` (for
# DashScope compatible mode this is ``{"enable_thinking": true}``). Mirrors the
# temperature flow: resolved once here, threaded through SpawnConfig, workflow
# execution, and SDK consumers, and overridable per role.
DEFAULT_THINKING = False
DEFAULT_THINKING_PARAMS: dict[str, Any] = {"enable_thinking": True}

# Truthy string tokens for boolean env vars ("1/true/yes/on").
_TRUTHY = frozenset({"1", "true", "yes", "on"})


def _parse_bool(value: str | None, *, default: bool = False) -> bool:
    """Parse a truthy env string ("1/true/yes/on") to bool; default on absence."""
    if value is None:
        return default
    return value.strip().lower() in _TRUTHY


def _parse_top_p(value: str | None) -> float | None:
    """Parse the top_p env string to ``float`` or ``None``.

    Unset or empty/whitespace-only → ``None`` (the provider default, request
    unchanged). A real number is returned as a float; range validation is left
    to the pydantic field so an out-of-range value fails loudly.
    """
    if value is None:
        return None
    stripped = value.strip()
    if not stripped:
        return None
    return float(stripped)


def _parse_thinking_params(value: str | None) -> dict[str, Any]:
    """Parse a JSON object string into a dict; fall back to the default.

    Invalid JSON (or a non-object payload) never crashes — the configured
    default ``{"enable_thinking": true}`` is used instead.
    """
    if not value:
        return dict(DEFAULT_THINKING_PARAMS)
    try:
        parsed = json.loads(value)
    except (json.JSONDecodeError, TypeError):
        return dict(DEFAULT_THINKING_PARAMS)
    if not isinstance(parsed, dict):
        return dict(DEFAULT_THINKING_PARAMS)
    return parsed


class OpenCollabConfig(BaseModel):
    """Runtime configuration for OpenCollab."""

    model_config = ConfigDict(extra="ignore")

    model: str = Field(default="gpt-4o", min_length=1)
    provider: str = Field(default="openai", min_length=1)
    wire_protocol: str = Field(default="chat_completions", min_length=1)
    api_key: str | None = Field(default=None, repr=False)
    base_url: str | None = None
    budget: int = Field(default=1_000_000, ge=1)
    temperature: float = Field(default=DEFAULT_TEMPERATURE, ge=0.0, le=2.0)
    top_p: float | None = Field(default=DEFAULT_TOP_P, ge=0.0, le=1.0)
    max_output_tokens: int = Field(default=DEFAULT_MAX_OUTPUT_TOKENS, ge=1)
    thinking: bool = Field(default=DEFAULT_THINKING)
    thinking_params: dict[str, Any] = Field(default_factory=lambda: dict(DEFAULT_THINKING_PARAMS))
    reasoning_effort: str | None = None
    llm_max_retries: int = Field(default=3, ge=0)
    llm_timeout: float = Field(default=600.0, gt=0, allow_inf_nan=False)
    llm_connect_timeout: float = Field(default=30.0, gt=0, allow_inf_nan=False)
    llm_first_event_timeout: float = Field(default=180.0, gt=0, allow_inf_nan=False)
    llm_stream_idle_timeout: float = Field(default=180.0, gt=0, allow_inf_nan=False)
    filter_messages: bool = Field(default=False)

    @field_validator("top_p", mode="before")
    @classmethod
    def _coerce_top_p(cls, value: Any) -> Any:
        # Accept the env/.env string form: empty/whitespace → None (unchanged
        # request), a real number → float. Mirrors temperature accepting its
        # string form, but defaults to None rather than a numeric default.
        if isinstance(value, str):
            return _parse_top_p(value)
        return value

    @field_validator("thinking", mode="before")
    @classmethod
    def _coerce_thinking(cls, value: Any) -> Any:
        # Accept the env/.env truthy string form ("1/true/yes/on") as well as a
        # real bool, mirroring how temperature accepts its string form.
        if isinstance(value, str):
            return _parse_bool(value)
        return value

    @field_validator(
        "llm_timeout",
        "llm_connect_timeout",
        "llm_first_event_timeout",
        "llm_stream_idle_timeout",
        mode="before",
    )
    @classmethod
    def _reject_boolean_llm_timeout(cls, value: Any) -> Any:
        if isinstance(value, bool):
            raise ValueError("LLM timeouts must be finite positive numbers")
        return value

    @field_validator("thinking_params", mode="before")
    @classmethod
    def _coerce_thinking_params(cls, value: Any) -> Any:
        # A JSON object string (from env/.env) parses to a dict; invalid JSON
        # falls back to the default rather than crashing.
        if isinstance(value, str):
            return _parse_thinking_params(value)
        if value is None:
            return dict(DEFAULT_THINKING_PARAMS)
        return value

    @field_validator("model", "provider", "wire_protocol", mode="before")
    @classmethod
    def _strip_required_strings(cls, value: Any) -> Any:
        if isinstance(value, str):
            return value.strip()
        return value

    @field_validator("provider")
    @classmethod
    def _normalize_provider(cls, value: str) -> str:
        return value.lower()

    @field_validator("wire_protocol")
    @classmethod
    def _normalize_wire_protocol(cls, value: str) -> str:
        return normalize_wire_protocol(value)

    @field_validator("reasoning_effort", mode="before")
    @classmethod
    def _normalize_reasoning_effort(cls, value: Any) -> Any:
        if value is None:
            return None
        normalized = str(value).strip().lower()
        if not normalized:
            return None
        if normalized not in {"low", "medium", "high", "xhigh"}:
            raise ValueError("reasoning_effort must be low, medium, high, or xhigh")
        return normalized

    @field_validator("api_key", "base_url", mode="before")
    @classmethod
    def _empty_string_as_none(cls, value: Any) -> Any:
        if isinstance(value, str):
            stripped = value.strip()
            return stripped or None
        return value


def load_dotenv(path: str | None = None) -> dict[str, str]:
    """Parse a .env file into a dict. Handles quotes and comments."""
    env_path = path or os.path.join(os.getcwd(), ".env")
    result: dict[str, str] = {}

    try:
        inspected = os.lstat(env_path)
    except FileNotFoundError:
        return result
    if not stat.S_ISREG(inspected.st_mode):
        raise ValueError(f"config env path is not a regular file: {env_path}")

    text = read_regular_text(env_path, max_bytes=MAX_DOTENV_BYTES)
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip()
        # Remove surrounding quotes
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
            value = value[1:-1]
        result[key] = value

    return result


def _candidate_env_paths(workspace: str | None = None) -> list[str]:
    """Return config file candidates in priority order."""
    explicit = os.environ.get("OPENCOLLAB_CONFIG_FILE")
    if explicit:
        return [explicit]

    bases: list[Path] = []
    if workspace:
        bases.append(Path(workspace))
    bases.append(Path.cwd())

    paths: list[str] = []
    seen: set[str] = set()
    for base in bases:
        for candidate in (base / "configs" / ".env", base / ".env"):
            key = str(candidate.resolve() if candidate.exists() else candidate.absolute())
            if key not in seen:
                paths.append(str(candidate))
                seen.add(key)
    return paths


def load_config_env(workspace: str | None = None) -> dict[str, str]:
    """Load env-file defaults from configs/.env and legacy .env locations.

    Earlier paths have higher priority.
    """
    values: dict[str, str] = {}
    for path in _candidate_env_paths(workspace):
        for key, value in load_dotenv(path).items():
            values.setdefault(key, value)
    return values


def _is_dashscope_base_url(base_url: str | None) -> bool:
    lowered = (base_url or "").lower()
    return "dashscope" in lowered or "aliyuncs" in lowered


def api_key_env_precedence(provider: str | None, base_url: str | None = None) -> tuple[str, ...]:
    """Ordered API-key env vars to consult, most provider-specific first.

    Key specificity matters more than source: this keeps a generic exported
    ``OPENAI_API_KEY`` from being sent to a provider-specific compatible
    endpoint (DashScope) or to the native Anthropic path.
    """
    if _is_dashscope_base_url(base_url):
        return ("DASHSCOPE_API_KEY", "OPENCOLLAB_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY")
    if is_anthropic(provider):
        return ("ANTHROPIC_API_KEY", "OPENCOLLAB_API_KEY", "OPENAI_API_KEY", "DASHSCOPE_API_KEY")
    return ("OPENCOLLAB_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY", "DASHSCOPE_API_KEY")


def accepted_api_key_envs(provider: str | None, base_url: str | None = None) -> list[str]:
    """The env-var names a user can set to satisfy the API-key requirement.

    ``OPENCOLLAB_API_KEY`` plus the provider-specific key, with
    ``DASHSCOPE_API_KEY`` appended for a DashScope-compatible endpoint.
    """
    names = ["OPENCOLLAB_API_KEY", required_env_key(provider)]
    if _is_dashscope_base_url(base_url):
        names.append("DASHSCOPE_API_KEY")
    return list(dict.fromkeys(names))


def missing_api_key(provider: str | None, api_key: str | None, base_url: str | None = None) -> bool:
    """Whether no usable API key is resolvable for ``provider``.

    A non-empty ``api_key`` (already resolved, e.g. from ``build_config``)
    satisfies the requirement; otherwise consult the env vars in precedence
    order. Whitespace-only values do not count as present.
    """
    if api_key and api_key.strip():
        return False
    for key in api_key_env_precedence(provider, base_url):
        value = os.environ.get(key)
        if value and value.strip():
            return False
    return True


def build_config(workspace: str | None = None, overrides: dict[str, Any] | None = None) -> OpenCollabConfig:
    """Build and validate runtime configuration.

    Priority: environment variable > configs/.env > .env > built-in default
    """
    dotenv = load_config_env(workspace)

    def resolve(key: str, *fallback_keys: str, default: str | None = None) -> str | None:
        # Check env vars first (highest priority)
        val = os.environ.get(key)
        if val:
            return val
        for fk in fallback_keys:
            val = os.environ.get(fk)
            if val:
                return val
        # Check .env file
        val = dotenv.get(key)
        if val:
            return val
        for fk in fallback_keys:
            val = dotenv.get(fk)
            if val:
                return val
        return default

    def resolve_ordered(
        *keys: str, default: str | None = None, file_first: bool = False
    ) -> str | None:
        # For provider-specific secrets, key specificity matters more than
        # source. This prevents a generic exported OPENAI_API_KEY from being sent
        # to a provider-specific compatible endpoint such as DashScope.
        #
        # With file_first, the env FILE value of each key beats a shell export of
        # the same key. A stale shell ANTHROPIC_API_KEY/OPENAI_API_KEY then cannot
        # shadow the real provider key written to configs/.env.
        for key in keys:
            sources = (dotenv, os.environ) if file_first else (os.environ, dotenv)
            for source in sources:
                val = source.get(key)
                if val:
                    return val
        return default

    selected_overrides = {
        key: value for key, value in (overrides or {}).items() if value is not None
    }
    provider_value = selected_overrides.get("provider") or resolve(
        "OPENCOLLAB_PROVIDER", default="openai"
    )
    base_url_value = (
        selected_overrides["base_url"]
        if "base_url" in selected_overrides
        else resolve("OPENCOLLAB_BASE_URL", "OPENAI_BASE_URL")
    )
    api_key_value = selected_overrides.get("api_key") or resolve_ordered(
        *api_key_env_precedence(provider_value, base_url_value), file_first=True
    )

    values: dict[str, Any] = {
        "model": resolve("OPENCOLLAB_MODEL", default="gpt-4o"),
        "provider": provider_value,
        "wire_protocol": resolve("OPENCOLLAB_WIRE_PROTOCOL", default="chat_completions"),
        "api_key": api_key_value,
        "base_url": base_url_value,
        "budget": resolve("OPENCOLLAB_BUDGET", default="1000000"),
        "temperature": resolve("OPENCOLLAB_TEMPERATURE", default=str(DEFAULT_TEMPERATURE)),
        "top_p": resolve("OPENCOLLAB_TOP_P", default=None),
        "max_output_tokens": resolve(
            "OPENCOLLAB_MAX_OUTPUT_TOKENS", default=str(DEFAULT_MAX_OUTPUT_TOKENS)
        ),
        "thinking": resolve("OPENCOLLAB_THINKING", default=str(DEFAULT_THINKING)),
        "thinking_params": resolve("OPENCOLLAB_THINKING_PARAMS"),
        "reasoning_effort": resolve("OPENCOLLAB_REASONING_EFFORT"),
        "llm_max_retries": resolve("OPENCOLLAB_LLM_MAX_RETRIES", default="3"),
        "llm_timeout": resolve("OPENCOLLAB_LLM_TIMEOUT", default="600"),
        "llm_connect_timeout": resolve("OPENCOLLAB_LLM_CONNECT_TIMEOUT", default="30"),
        "llm_first_event_timeout": resolve(
            "OPENCOLLAB_LLM_FIRST_EVENT_TIMEOUT", default="180"
        ),
        "llm_stream_idle_timeout": resolve(
            "OPENCOLLAB_LLM_STREAM_IDLE_TIMEOUT", default="180"
        ),
        "filter_messages": resolve("OPENCOLLAB_FILTER_MESSAGES", default="false"),
    }
    values.update(selected_overrides)
    return OpenCollabConfig.model_validate(values)


def get_config(workspace: str | None = None) -> dict[str, Any]:
    """Get resolved configuration as a dict for existing callers."""
    return build_config(workspace).model_dump()
